apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: qbsd4pl30-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/qbsd4pl30-java-quarkus-gitops